#!/bin/sh

ACTION="$1"

init() ## Initialize-your-sphinx-document
{
    type docker-compose >/dev/null 2>&1
    if [ $? -ne 0 ]; then
        echo "docker-composeないよ"
        exit 1
    fi

    read -p "Input your project name: " Project
    read -p "Input author name: " Author
    docker-compose run --rm docs-builder sphinx-quickstart -q -p ${Project} -a ${Author} -v 1.0.0 --sep --no-batchfile
}

watch() ## Watch-files-and-automatically-refresh-your-browser
{
    docker-compose run --rm docs-builder sphinx-autobuild -b html source build/html -H 0.0.0.0
    type open >/dev/null 2>&1
    if [ $? -eq 0 ]; then
        open http://localhost:8000
    fi
}

help() ## Show-this-help-text
{
    [ -z "$1" ] || printf 'Error: %s\n' "$1"
    echo

    echo '\033[33mUsage:\033[m'
    echo " ./manage [command]"
    echo

    echo '\033[33mCommands:\033[m'
    # grep "^function.*##" $0 | sed -e 's/ \{1,\}/ /g;s/function //;s/() ## / /' | awk '{printf "\033[36m%-30s\033[0m %s\n", $1, $2}'
    grep -E '^(function\s+)?\w+\(\)\s+\{?\s*##' $0 | sed -e 's/{//;s/ \{1,\}/ /g;s/function //;s/() ## / /' | awk '{printf " \033[36m%-20s\033[0m %s\n", $1, $2}'

}

if [ -n "$(type -t $ACTION)" ] && [ "$(type -t $ACTION)" = function ]; then
     $ACTION $@
 else
     help "action not found"
fi

# Refs:
# シェルスクリプトの出力に色をつけたい！
# https://qiita.com/dojineko/items/49aa30018bb721b0b4a9